chore: update githooks for commit automation
- Introduces post-commit hook to run tests and reset on failure
- Includes pre-push hook to build and verify Docker images
- Configures branches to skip hooks and adds manual skip option
- Adds a README for githook setup and usage instructions

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -11,8 +11,8 @@ BRANCH_NAME=$(git branch --show-current | grep -E "$listRE" | sed 's/* //')
 
 printf '\n\033[0;105mChecking "%s"... \033[0m\n' "$BRANCH_NAME"
 
-if echo "$BRANCH_NAME" | grep -q '^(rebase)|(production)*$'; then
- 	printf '\n\033[0;32mNo checks necessary on "%s", pushing now... 🎉\033[0m\n' "$BRANCH_NAME"
+if echo "$BRANCH_NAME" | grep -q '^(hotfix)|(rebase)|(production)*$'; then
+ 	printf '\n\033[0;32mNo checks necessary on "%s", skipping hooks... 🎉\033[0m\n' "$BRANCH_NAME"
 	exit 0
 fi
 # Check for existence of "new or modified" files
@@ -25,23 +25,24 @@ else
   DOCKER_BUILD_EXIT_CODE=$?
 fi
 
-
-if [ -n "$TEST_FILES" ]; then
-  printf '\nRunning Rails Tests...'
-  make test
-  RUBY_TEST_EXIT_CODE=$?
-  WORK_DONE=1
-else
-  RUBY_TEST_EXIT_CODE=0
-fi
-
-if [ ! $RUBY_TEST_EXIT_CODE -eq 0 ]; then
-  printf '\n\033[0;31mCannot push, tests are failing. Use --no-verify to force push. 😖\033[0m\n'
+if [ $DOCKER_BUILD_EXIT_CODE -ne 0 ]; then
+  printf '\n\033[0;31mDocker image build failed. Please check your changes. 😖\033[0m\n'
   exit 1
+else
+  printf '\n\033[0;32mDocker image build succeeded. 🎉\033[0m\n'
+  CONTAINER_ID=$(AWS_PROFILE=$CLIENT_PROFILE API_SERVICE_URL=$API_SERVICE_URL make run | tail -1)
+  printf '\n\033[0;33mRunning Docker image %s ... \033[0m\n' "$CONTAINER_ID"
+  sleep 10
+  docker inspect --format="{{.State.Running}}" "$CONTAINER_ID" | grep 'true' -q
+  DOCKER_RUN_EXIT_CODE=$?
+  printf '\n\033[0;33mStopping Docker image with exit code %s ... \033[0m\n' "$DOCKER_RUN_EXIT_CODE"
+  docker stop "$CONTAINER_ID" > /dev/null 2>&1
 fi
 
-if [ $WORK_DONE = 1 ]; then
-  printf '\n\033[0;32mAll tests are green, pushing... 🎉\033[0m\n'
+if [ $DOCKER_RUN_EXIT_CODE -ne 0 ]; then
+  printf '\n\033[0;31mDocker image run failed. Please check your changes. 😖\033[0m\n'
+  exit 1
+else
+  printf '\n\033[0;32mDocker image run succeeded. 🎉\033[0m\n'
+  exit 0
 fi
-
-exit 0
